language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: pages
  target-branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: dev
